### PR TITLE
App Menu

### PR DESCRIPTION
**Pull request by somas95**
- [x]  Refactored the window code
- [x]  Added an Application Menu (with a menu scheme proposal)
- [x]  Added a working "About" dialog (in the application menu)

### CODE REVIEW

**Comment by somas95** [comment]
- [x] Added a functional gtkShortcutWindow to the appMenu
- [x] Added a link to the online Pandoc help to the appMenu
- [x] Small fixes, refactoring, deleted unused files and functions

**Comment by wolfv** [comment]
Hey, just tried it! Looks great!

One thing was missing from the About Dialog though -- your name! ;) You're more than welcome to add yourself, otherwise I'll do it, of course...

Let me know if you think it's ready to be merged :)

**Comment by somas95** [comment]
Sure! I'll add it to the contributors list.
If you want to merge it, all the app menu related things are done, but I want to fix two bugs:
- Links in the preview mode are opened in the same WebView, not in the browser
- Files are not loaded if they are opened from the file explorer
If you merge this now, I'll push the fixes to your repo directly. Maybe the second bug is related to the refactoring of the window code, so if you want to hold until I fix that, it's also ok

**Comment by somas95** [comment]
- [x] Fixed the policy request issues in the preview (aka opening links in Uberwriter vs in the browser)
- [x] Fixed the regression that caused Uberwriter to not load files from terminal or file manager
- [x] Added support for GMF checkboxes 
- [x] Cleaned up some errors that were showed when launching from terminal

That said, the terminal arguments parsing is gone, so launching with -v or -e does nothing. I want to update the parsing to use sys.argv
Another thing that currently it's not supported is the ability to open multiple instances of the application.

**Pull request merged**
