### PR TITLE
Fixed HeaderBar issues

### PR DESCRIPTION
**Pull request by somas95**
HeaderBar vanishes to the background color (in white and dark modes)

### CODE REVIEW

**Comment by wolfv** [comment]
Looks good to me! Merge?

**Comment by somas95** [comment]
I think so! If you want to play with it before do it, for me works flawlessly  :)

**Comment by wolfv** [comment]
by the way, do you see the cursor?

**Comment by somas95** [comment]
Yes, but in Arc theme is barely noticeable. In Adwaita it's in pure 
black

En lun, 11 de dic 2017 a les 5:00 P. M., Wolf Vollprecht 
<notifications@github.com> ha escrit:

**Comment by somas95** [comment]
The theme switcher in the gtk inspector is a really time saver testing 
this style things
In arc-dark the bottom labels are very difficult to read too


En lun, 11 de dic 2017 a les 5:02 P. M., Manuel 
<manuel.genoves@gmail.com> ha escrit:

**Comment by somas95** [comment]
Ugh, the autocorrect

The theme switcher of the gtk inspector is really a time saver for testing
issues like this

With arc-dark the bottom labels are very difficult to read too

**Pull request merged**
