### PR TITLE
add flatpak config

### PR DESCRIPTION
**Pull request by wolfv**

### CODE REVIEW

**Comment by wolfv** [comment]
Hey @somas95 

I have merged this already so that it works (because the uberwriter.json is configured to the master branch).

If you have flatpak-builder installed, you should be able to build an uberwriter flatpak relatively easily from the command line using the following commands:

-- cd to the `flatpak` dir of the repo
-- `flatpak-builder --install --force-clean some_folder_name uberwriter.json`  # this installs and cleans the build folder)
-- `flatpak run de.wolfvollprecht.UberWriter`
-- you can also debug with the following: `flatpak-builder --run --share=network some_folder_name uberwriter.json sh`

Let me know if it works for you! Looked good for me so far! :) 

Fonts are installed correctly now (at the moment fira mono, as indicated in the CSS), and pandoc is also installed (by extracting the binaries from the debian package from github :) 
I am pretty happy with this setup .. also at some points it can surely be refined.

Also note that I had to change setup.py to not use the distutilsextra stuff ... i did this a long time ago and forgot what I did... We might have to test that it's still possible to install this in the regular, python way (if we want to support that)...

**Comment by somas95** [comment]
All works perfectly :+1: 
Also building it with setup.py
I'll update the README to reflect this

**Comment by wolfv** [comment]
Cool! Great to hear :)

2018-04-05 13:14 GMT+02:00 somas95 <notifications@github.com>:

**Comment by somas95** [comment]
Hmm... I just noticed that installing with `flatpak-builder --install --force-clean some_folder_name uberwriter.json` doesn't install any .desktop file...

**Comment by wolfv** [comment]
hmm, all we have at the moment is the `uberwriter.desktop.in` at the moment, right? did you add some code to rename it in the setup process?

**Comment by wolfv** [comment]
(you only renamed the icon, if i saw that correctly)

**Comment by somas95** [comment]
Yes, I only renamed the icon. In my computer renaming the .desktop does nothing...

**Comment by somas95** [comment]
It seems that the .desktop issue was a bug in flatpak-builder when using the --install flag:
https://github.com/flatpak/flatpak-builder/pull/124
It's already fixed, and the files convently renamed on this repo, so theoricatly it will work in a near future

**Comment by wolfv** [comment]
nice, cool for noticing it.

**Pull request merged**
