### PR TITLE
fix typo in flatpak definition

### PR DESCRIPTION
**Pull request by njam**
Nice app!
Took me some time to install it though.
Would be great if there was a simple way to download the flatpak.
How about submitting it to Flathub? https://github.com/flathub/flathub/wiki/App-Submission

### CODE REVIEW

**Comment by njam** [comment]
Nice!
Installing and running it on Gnome works fine. Two possibly flatpak-related issues I noticed:

1. When trying to export as PDF it fails with this error:
```
pdflatex not found. Please select a different --pdf-engine or install pdflatex
```
I have this executable on my machine. Does it need to be added to the Flatpak?


2. And opening *preview* fails with:
```
Traceback (most recent call last):
  File "/app/lib/python3.5/site-packages/uberwriter-1.0-py3.5.egg/uberwriter/UberwriterWindow.py", line 711, in toggle_preview
    '--lua-filter=' + helpers.get_script_path('relative_to_absolute.lua'),
TypeError: Can't convert 'NoneType' object to str implicitly
```

**Comment by wolfv** [comment]
ah, yes, true. slipped my mind that we'll also have to ship latex in the flatpak ... argh. That might increase the flatpak size considerably. I'll have to figure out a way to install latex in the flatpak.
I'll create an issue for that. 

The second one looks like a "simple" python bug? Although I haven't noticed it. Probably get_script_path returning None.

**Comment by somas95** [comment]
The second one is solved by 1f73258ae25b622a2b2a2b63fb4aeb46f6e93ed1

**Comment by somas95** [comment]
> ah, yes, true. slipped my mind that we'll also have to ship latex in the flatpak ... argh. That might increase the flatpak size considerably.

While that's true, seems that if the user installs different flatpaks that ship the same version of latex, all they will share only one latex runtime
See [this related conversation](https://lists.freedesktop.org/archives/flatpak/2016-June/000255.html)

**Pull request merged**
